"use strict";
let myname = document.getElementById("name");
let desig = document.getElementById("desig");
let phone = document.getElementById("phone");
let email = document.getElementById("email");
let Address = document.getElementById("Address");
let passing = document.getElementById("Passing");
let Education = document.getElementById("Education");
let institute = document.getElementById("institute");
let skills1 = document.getElementById("skills1");
let skills2 = document.getElementById("skills2");
let skills3 = document.getElementById("skills3");
let lang = document.getElementById("lang");
let lang2 = document.getElementById("lang2");
let styear = document.getElementById("styear");
let endyear = document.getElementById("endyear");
let company = document.getElementById("company");
let Job = document.getElementById("Job");
let submitbtn = document.getElementById("submitbtn");
let form = document.getElementById("form");
form?.addEventListener("submit", (e) => {
    e.preventDefault();
    localStorage.setItem("name", myname.value);
    localStorage.setItem("desig", desig.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("Address", Address.value);
    localStorage.setItem("passing", passing.value);
    localStorage.setItem("Education", Education.value);
    localStorage.setItem("institute", institute.value);
    localStorage.setItem("skills1", skills1.value);
    localStorage.setItem("skills2", skills2.value);
    localStorage.setItem("skills3", skills3.value);
    localStorage.setItem("lang", lang.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("styear", styear.value);
    localStorage.setItem("endyear", endyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("Job", Job.value);
});
